### ISSUE TITLE
Since the staticman comments are broken, I thought I would ask my question here

### ISSUE THREAD

**Issue by subnut** [EdwinWenink/personal_website#1711]
In [this screencast](https://www.edwinwenink.xyz/posts/48-vim_fast_creating_and_linking_notes/#screencast), I noticed that there are some blue vertical bars in the signcolumn, but the very first line is a hyphen.

Which plugin is producing that? What is that supposed to indicate?  
Just curious 😅 

  
  
---
I googled [_vim zettlekasten_](https://www.google.com/search?q=vim+zettelkasten), and that blogpost of yours was the second result. That's how I discovered your blog.

**Comment by EdwinWenink** [comment]
Hi, thanks for reaching out! It's pretty cool that my post is so high up in the search results. I'm fairly certain that the syntax plugin for [vim pandoc](https://github.com/vim-pandoc/vim-pandoc-syntax) does that. It automatically creates folds for markdown headers and for example also replaces the '#' with paragraphs symbols if you have `set conceallevel=1`. Anyways, the hyphen indicates that a fold is opened. If the fold is closed it will show a `+` instead. It also shows the header level. So if I'm in a subheader it will additionally show `2` in the sign column. Feel free to let me know if it doesn't work for you (and of course if it does)!

**Comment by subnut** [comment]
Thanks for the detailed description! 👍   

Will try it out later.
