### ISSUE TITLE
building a note-taking system with vanilla vim

### ISSUE THREAD

**Issue by anthrolisp** [EdwinWenink/personal_website#559]
Thank you for your blog post, "[building a note-taking system with vanilla vim](https://www.edwinwenink.xyz/posts/42-vim_notetaking/)." I'm currently in the process of migrating from emacs (and [zetteldeft](https://github.com/EFLS/zetteldeft) for note taking and writing. I wanted to something simpler, and also easier to maintain across both my personal Linux setup and work Windows machine. I was initially inspired to move to vim from this [Vim-Based Integrated Research Environment](https://github.com/Hipomenes/vim-ide) (see also [this ](http://davidcolmenares.org/convivial.tools/david-s-integrated-research-environment) and [this](http://davidcolmenares.org/dh-tools/quick-wiki-links)). I'm really enjoying my new setup, and am looking forward to seeing follow-up posts. Many thanks again!

**Comment by EdwinWenink** [comment]
Thanks a lot for your feedback! This is a big coincidence, but I actually found time today to write a new blogpost. I just finished it and am quite content with it. It is a tutorial for a sensible tagging system that that I've come up with last week.  The system is in principle editor agnostic but works perfectly in Vim. 
Thanks for those links, I did not know them yet and they in turn link to other interesting reads, so I'll definitely have fun with that. Two remarks:

- Feel free to leave a comment under the post itself through my hacked-together comment system that runs on a Raspberry Pi :-) 
- I'm definitely curious about your ideas on this subject. Just letting you know that I do accept fitting guest contributions ;-).

**Comment by anthrolisp** [comment]
Looking forward to reading the new blog post. I just opened up!
What would be of tremendous help is if at the end you summarized everything that goes into the vimrc to replicate the setup.
Thank you again!!

**Comment by EdwinWenink** [comment]
Good point! I'll do that as soon as I have time, maybe later tonight. If at some point I've reached a final workflow, I should dedicate some time on making a minimal vimrc available as well. I do have my [vimrc](https://github.com/EdwinWenink/.dotfiles/blob/master/vim/.vimrc) online but it's ... messy :-).

**Comment by EdwinWenink** [comment]
See [here](https://www.edwinwenink.xyz/posts/43-notes_tagging/#conclusion-and-summary-of-used-vim-mappings) for an overview of all used .vimrc settings (including those from the previous post). 
I'll close this issue, feel free to reopen if needed.
